import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './styles/tailwind.css'
import App from './App.tsx'

// Suppress a known-benign Chrome error generated by the Google Identity
// Services (GIS) / Drive Picker libraries when the OAuth popup closes before
// Chrome's internal message channel has finished its handshake.  The error is
// an unhandled Promise rejection originating inside Google's own scripts; it
// does not affect application functionality.
//
// The full verbatim Chrome error string is matched to avoid accidentally
// silencing unrelated errors from other libraries.
const GIS_CHANNEL_ERROR =
  'A listener indicated an asynchronous response by returning true, ' +
  'but the message channel closed before a response was received';

window.addEventListener('unhandledrejection', (event: PromiseRejectionEvent) => {
  const msg: unknown =
    event.reason instanceof Error ? event.reason.message : event.reason;
  if (typeof msg === 'string' && msg.includes(GIS_CHANNEL_ERROR)) {
    event.preventDefault();
  }
});

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)

// ── Service Worker registration ──────────────────────────────────────────────
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch((err) => {
      console.warn('SW registration failed:', err);
    });
  });
}
